services:
  auth_server:
    build:
      context: ./auth_server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    container_name: flask-auth-server

  resource_server:
    build:
      context: ./resource_server
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    container_name: flask-resource-server
